name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*' # 监听所有 v 开头的 tag，比如 v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 你项目用的 Node 版本

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip build output
        run: |
          cd dist
          zip -r ../build.zip ./
        # 假设 Vite 构建产物在 dist 目录

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
